version: '3.4'

services:
  api:
    container_name: k8snet-api
    ports:
        - "8080:80"
    image: ${DOCKER_REGISTRY-}k8snet-api
    volumes:
      - /home:/hostpipe
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    build:
      context: .
      dockerfile: ApiDockerfile
  socket-server:
    container_name: k8snet-socket-server
    ports:
        - "80:80"
    image: ${DOCKER_REGISTRY-}k8snet-socket-server
    build:
      context: .
      dockerfile: SocketServerDockerfile
  mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: lunsztra
    ports:
      - 27017:27017
    #volumes:
    #  - ./Docker/volumes/mongo-db:/data/db
  #selenium:
  #  image: selenium/standalone-chrome
  #  ports:
  #    - 4444:4444
