version: '3.4'

services:
  react-app:
    container_name: projack
    ports:
        - "80:80"
    image: ${DOCKER_REGISTRY-}projack
    volumes:
      - ./Docker/volumes/sql-server-volume:/home/sql-server-volume
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    build:
      context: .
      dockerfile: ReactAppDockerfile