version: '3.4'

services:
  api:
    container_name: k8snet-api
    ports:
        - "8080:80"
    image: ${DOCKER_REGISTRY-}k8snet-api
    volumes:
      - ./Docker/volumes/sql-server-volume:/home/sql-server-volume
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    build:
      context: .
      dockerfile: ReactAppDockerfile